Attempt to fix some of the testing errors.  Need to fix section beginning at line122.
functions.build_images(test_vars[0], test_vars[3])
Building changed Dockerfiles...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/s181706.SWMED/OneDrive - University of Texas Southwestern/Documents/GitHub/auto-docker/scripts/functions.py", line 122, in build_images
    print(temp_array)
TypeError: object of type 'builtin_function_or_method' has no len()